/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./components/AppPage.vue')['default']
    ExactFileDetailCard: typeof import('./components/exact/ExactFileDetailCard.vue')['default']
    ExactGroupContent: typeof import('./components/exact/ExactGroupContent.vue')['default']
    ExactGroupMeta: typeof import('./components/exact/ExactGroupMeta.vue')['default']
    ExactMacOpenCommandRow: typeof import('./components/exact/ExactMacOpenCommandRow.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLi: typeof import('naive-ui')['NLi']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NUl: typeof import('naive-ui')['NUl']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UncertainFetchState: typeof import('./components/uncertain/UncertainFetchState.vue')['default']
    UncertainFileDetailCard: typeof import('./components/uncertain/UncertainFileDetailCard.vue')['default']
    UncertainMatchIntro: typeof import('./components/uncertain/UncertainMatchIntro.vue')['default']
    UncertainPairContent: typeof import('./components/uncertain/UncertainPairContent.vue')['default']
    UncertainPairMeta: typeof import('./components/uncertain/UncertainPairMeta.vue')['default']
    UncertainPreviewGrid: typeof import('./components/uncertain/UncertainPreviewGrid.vue')['default']
  }
}
